services:
  bio-frontend:
    image: yxzhin/bio:latest
    restart: unless-stopped
    networks:
      - internal
      - proxy

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - bio-frontend

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
  proxy:
    external: true
